#define LIGHT_BEDROOM2_1			1
#define LIGHT_BEDROOM2_2			2
#define LIGHT_BEDROOM2_3			3		
#define LIGHT_BEDROOM2_4			4

#define SOULISS_GLOBALS

#define SOULISS_DEFINE_TYPICALS	Set_LightsGroup(LIGHT_BEDROOM2_1, LIGHT_BEDROOM2_4);

#define SOULISS_READ_INPUTS 	ssLightsGroupIN(IN1, LIGHT_BEDROOM2_1, LIGHT_BEDROOM2_4);

#define SOULISS_PROCESS_LOGICS 	Logic_LightsGroup(LIGHT_BEDROOM2_1, LIGHT_BEDROOM2_4);

#define SOULISS_SET_OUTPUTS 	CntRelay1(LIGHT_BEDROOM2_1);\
								CntRelay2(LIGHT_BEDROOM2_2);\
								CntRelay3(LIGHT_BEDROOM2_3);\
								CntRelay4(LIGHT_BEDROOM2_4);

#define SOULISS_PROCESS_TIMERS 	Timer_LightsGroup(LIGHT_BEDROOM2_1, LIGHT_BEDROOM2_4);