#define	DHT_SENSOR			1 // define DHT_SENSOR with highest index

#define SOULISS_GLOBALS

#define SOULISS_DEFINE_TYPICALS	

#define SOULISS_READ_INPUTS 	

#define SOULISS_PROCESS_LOGICS 	

#define SOULISS_SET_OUTPUTS 	

#define SOULISS_PROCESS_TIMERS 	